添加webp转png功能，支持在config文件中修改所用api
Samarium150/mirai-console-loafers-calendar pull request #4
Opened 2023-03-16 20:19 UTC by c-nameless

2023-03-16 20:39 UTC, Samarium150 commented on src/main/kotlin/util/General.kt
> +    if(api == "https://j4u.ink/moyuya" || api == "https://j4u.ink/moyuya/") {
这个if为什么要用or链接两个一样的条件

2023-03-16 20:42 UTC, Samarium150 requested changes
`https://api.vvhan.com/api/moyu`这个api从境外访问是必定会502的，我不认为有引入的必要

2023-03-16 22:56 UTC, c-nameless commented
考虑到使用插件的用户群体，绝大部分应该都没有这个问题。且可以在config文件中自由切换所用的api，一个出问题后，可以随时切换到另一个。因此，我仍希望两个api都保留，选择权交给用户，在文档中说明问题即可。

2023-03-16 23:05 UTC, c-nameless commented
考虑到使用插件的用户群体，绝大部分应该都没有这个问题。且可以在config文件中自由切换所用的api，一个出问题后，可以随时切换到另一个。因此，我仍希望两个api都保留，选择权交给用户，在文档中说明问题即可。

2023-03-17 00:19 UTC, Samarium150 reviewed
我等会儿会重写一下webp转png的实现。至于修改api，我不认为有必要给用户提供这个选择权。就算提供了，现在的实现也是有问题的。

2023-03-17 00:19 UTC, Samarium150 commented on src/main/kotlin/util/General.kt
> +    if (j4uApi && !isSunday(target) && response.etag() == "\"6251bbbb-d2781\"")
为什么不为另一个api检查图片是否更新

2023-03-17 00:19 UTC, Samarium150 commented on src/main/kotlin/util/General.kt
> +    val response: HttpResponse = httpClient.get(api)
这里如果用户随便写了个url在config里，GET请求获取到的内容是不可预测的

2023-03-17 00:19 UTC, Samarium150 commented on src/main/kotlin/util/General.kt
> +    if(j4uApi && isWebPImage(body))
使用`Content-Type`即可检查响应的内容类型

2023-03-17 00:28 UTC, Samarium150 approved these changes

2023-03-17 00:33 UTC, merged